# Generated by Django 2.2 on 2019-05-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190502_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-reg_time'], 'verbose_name': '用户名', 'verbose_name_plural': '用户名'},
        ),
    ]
