# Generated by Django 2.2 on 2019-05-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='姓名')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('tel', models.CharField(max_length=15, verbose_name='电话')),
                ('hometown', models.CharField(max_length=100, verbose_name='故乡')),
                ('address', models.CharField(max_length=100, verbose_name='所在地')),
                ('university', models.CharField(max_length=50, verbose_name='大学')),
                ('company', models.CharField(max_length=50, verbose_name='公司')),
                ('profession', models.CharField(max_length=20, verbose_name='职业')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='用户')),
            ],
        ),
    ]
