# Generated by Django 2.2 on 2019-05-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_user_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='信息')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('receiver', models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='receiver', to='users.User', verbose_name='接收方')),
                ('sender', models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sender', to='users.User', verbose_name='发送方')),
            ],
        ),
    ]
