# Generated by Django 2.2 on 2019-05-12 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='msg',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
