# Generated by Django 2.2 on 2019-05-13 09:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_auto_20190512_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='msg',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
