# Generated by Django 2.2 on 2019-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0004_auto_20190513_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='msg',
            field=models.CharField(max_length=200, verbose_name='消息'),
        ),
    ]
